--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALLOWANCE
--------------------------------------------------------

  CREATE TABLE "ERP"."ALLOWANCE" 
   (	"ID" NUMBER(4,0), 
	"OVERTIME" NUMBER DEFAULT 0.00, 
	"MEDICAL" NUMBER DEFAULT 0.00, 
	"BONUS" NUMBER DEFAULT 0.00, 
	"OTHER" NUMBER DEFAULT 0.00, 
	"EMP_ID" NUMBER, 
	"SALARY" NUMBER DEFAULT NULL, 
	"RATE" NUMBER DEFAULT NULL, 
	"TOTAL_ALLOWANCE" NUMBER, 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUDIT_TABLE
--------------------------------------------------------

  CREATE TABLE "ERP"."AUDIT_TABLE" 
   (	"AUDIT_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"DATE_OF_AUDIT" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEDUCTION
--------------------------------------------------------

  CREATE TABLE "ERP"."DEDUCTION" 
   (	"ID" NUMBER(5,0), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"SALARY" VARCHAR2(20 BYTE) DEFAULT 0.00, 
	"DEDUCTION_AMOUNT" VARCHAR2(20 BYTE), 
	"DEDUCTION_REASON" VARCHAR2(30 BYTE), 
	"EMP_ID" VARCHAR2(20 BYTE), 
	"MADE_BY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF_INFORMATION
--------------------------------------------------------

  CREATE TABLE "ERP"."STAFF_INFORMATION" 
   (	"ID" NUMBER(4,0), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"DOB" VARCHAR2(20 BYTE) DEFAULT null, 
	"EMAIL" VARCHAR2(40 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"DEPARTMENT" VARCHAR2(30 BYTE), 
	"IMAGE" BLOB, 
	"GENDER" VARCHAR2(10 BYTE), 
	"SALARY" NUMBER, 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"APARTMENT" VARCHAR2(50 BYTE), 
	"POST_CODE" VARCHAR2(20 BYTE) DEFAULT null, 
	"DESIGNATION" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"DATE_HIRED" VARCHAR2(20 BYTE), 
	"JOB_TITLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ERP"."USERS" 
   (	"ID" NUMBER(4,0), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"DIVISION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS_INFORMATION
--------------------------------------------------------

  CREATE TABLE "ERP"."USERS_INFORMATION" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"DIVISION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ALLOWANCE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."ALLOWANCE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ALLOWANCE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."ALLOWANCE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ALLOWANCE_SEQUENCE_1
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."ALLOWANCE_SEQUENCE_1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ALLOWANCE_TABLE
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."ALLOWANCE_TABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUDITTABLE
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."AUDITTABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUDIT_FOR_AUDIT
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."AUDIT_FOR_AUDIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUDIT_FOR_TABLE
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."AUDIT_FOR_TABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence AUDIT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."AUDIT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEDUCTION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."DEDUCTION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEDUCTION_STARTS
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."DEDUCTION_STARTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEDUCTION_TABLE
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."DEDUCTION_TABLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMP_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."EMP_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ERP_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."ERP_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE_AUDIT
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."TABLE_AUDIT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE_AUDIT_1
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."TABLE_AUDIT_1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TABLE_AUDIT_2
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."TABLE_AUDIT_2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_INFORMATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."USERS_INFORMATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ERP"."USER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ERP.ALLOWANCE
SET DEFINE OFF;
Insert into ERP.ALLOWANCE (ID,OVERTIME,MEDICAL,BONUS,OTHER,EMP_ID,SALARY,RATE,TOTAL_ALLOWANCE,FIRST_NAME,SURNAME,CREATED_BY) values (1,50,20,30,40,4,100000,500,8850,'ammar','ejaz','0');
Insert into ERP.ALLOWANCE (ID,OVERTIME,MEDICAL,BONUS,OTHER,EMP_ID,SALARY,RATE,TOTAL_ALLOWANCE,FIRST_NAME,SURNAME,CREATED_BY) values (21,50,50,50,50,2,500000,2500,198750,'hammad','ejaz','0');
REM INSERTING into ERP.AUDIT_TABLE
SET DEFINE OFF;
Insert into ERP.AUDIT_TABLE (AUDIT_ID,EMP_ID,DATE_OF_AUDIT,STATUS) values (1,0,'13:06:56 / Mar 26, 2017','Logged in');
Insert into ERP.AUDIT_TABLE (AUDIT_ID,EMP_ID,DATE_OF_AUDIT,STATUS) values (2,0,'13:12:56 / Mar 26, 2017','Logged out');
REM INSERTING into ERP.DEDUCTION
SET DEFINE OFF;
Insert into ERP.DEDUCTION (ID,FIRST_NAME,SURNAME,SALARY,DEDUCTION_AMOUNT,DEDUCTION_REASON,EMP_ID,MADE_BY) values (1,'ammar','ejaz','250000','75000',null,'4','0');
REM INSERTING into ERP.STAFF_INFORMATION
SET DEFINE OFF;
Insert into ERP.STAFF_INFORMATION (ID,FIRST_NAME,SURNAME,DOB,EMAIL,TELEPHONE,ADDRESS,DEPARTMENT,GENDER,SALARY,ADDRESS2,APARTMENT,POST_CODE,DESIGNATION,STATUS,DATE_HIRED,JOB_TITLE) values (4,'ammar','ejaz',null,'maaz@yahoo.com',null,null,null,'Male',null,null,null,null,null,null,null,null);
Insert into ERP.STAFF_INFORMATION (ID,FIRST_NAME,SURNAME,DOB,EMAIL,TELEPHONE,ADDRESS,DEPARTMENT,GENDER,SALARY,ADDRESS2,APARTMENT,POST_CODE,DESIGNATION,STATUS,DATE_HIRED,JOB_TITLE) values (2,'hammad','ejaz',null,'hammadejaz@yahoo.com',null,null,null,'Male',null,null,null,null,null,null,null,null);
Insert into ERP.STAFF_INFORMATION (ID,FIRST_NAME,SURNAME,DOB,EMAIL,TELEPHONE,ADDRESS,DEPARTMENT,GENDER,SALARY,ADDRESS2,APARTMENT,POST_CODE,DESIGNATION,STATUS,DATE_HIRED,JOB_TITLE) values (22,'hammad','nakhuda','22/05/1996','m.ammarejaz@yahoo.com','02134961768','babe rehmat','CIS','Male',250000,'akber arcade','flat 9','2252','MANAGER','Active','22/05/1996','MANAGER');
Insert into ERP.STAFF_INFORMATION (ID,FIRST_NAME,SURNAME,DOB,EMAIL,TELEPHONE,ADDRESS,DEPARTMENT,GENDER,SALARY,ADDRESS2,APARTMENT,POST_CODE,DESIGNATION,STATUS,DATE_HIRED,JOB_TITLE) values (21,'hammad','ejaz',null,'m.hammadejaz@yahoo.com',null,null,'CIS','Male',220000,null,null,null,'Manager',null,null,null);
REM INSERTING into ERP.USERS
SET DEFINE OFF;
Insert into ERP.USERS (ID,USERNAME,PASSWORD,DIVISION) values (1,'hammad','hammad','admin');
REM INSERTING into ERP.USERS_INFORMATION
SET DEFINE OFF;
Insert into ERP.USERS_INFORMATION (ID,USERNAME,PASSWORD,DIVISION) values (1,'hammad','hammad','admin');
--------------------------------------------------------
--  DDL for Index ALLOWANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."ALLOWANCE_PK" ON "ERP"."ALLOWANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_INFORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."USERS_INFORMATION_PK" ON "ERP"."USERS_INFORMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEDUCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."DEDUCTION_PK" ON "ERP"."DEDUCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AUDIT_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."AUDIT_TABLE_PK" ON "ERP"."AUDIT_TABLE" ("AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAFF_INFORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."STAFF_INFORMATION_PK" ON "ERP"."STAFF_INFORMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERP"."ID_PK" ON "ERP"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger USERS_INFORMATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ERP"."USERS_INFORMATION_TRG" 
BEFORE INSERT ON USERS_INFORMATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_INFORMATION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
    IF INSERTING AND :NEW.DIVISION IS NULL THEN
      SELECT USERS_INFORMATION_SEQ.NEXTVAL INTO :NEW.DIVISION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ERP"."USERS_INFORMATION_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEDUCTION
--------------------------------------------------------

  ALTER TABLE "ERP"."DEDUCTION" ADD CONSTRAINT "DEDUCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."DEDUCTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS_INFORMATION
--------------------------------------------------------

  ALTER TABLE "ERP"."USERS_INFORMATION" ADD CONSTRAINT "USERS_INFORMATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."USERS_INFORMATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDIT_TABLE
--------------------------------------------------------

  ALTER TABLE "ERP"."AUDIT_TABLE" ADD CONSTRAINT "AUDIT_TABLE_PK" PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."AUDIT_TABLE" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ERP"."USERS" ADD CONSTRAINT "ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."USERS" MODIFY ("PASSWORD" CONSTRAINT "PA_NN" NOT NULL ENABLE);
  ALTER TABLE "ERP"."USERS" MODIFY ("USERNAME" CONSTRAINT "US_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_INFORMATION
--------------------------------------------------------

  ALTER TABLE "ERP"."STAFF_INFORMATION" ADD CONSTRAINT "STAFF_INFORMATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."STAFF_INFORMATION" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ERP"."STAFF_INFORMATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALLOWANCE
--------------------------------------------------------

  ALTER TABLE "ERP"."ALLOWANCE" ADD CONSTRAINT "ALLOWANCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERP"."ALLOWANCE" MODIFY ("ID" NOT NULL ENABLE);
